Correction of all assignments
AlreadyBored/nodejs-assignments pull request #22
Opened 2022-06-04 22:31 UTC by ML6503

2022-06-05 13:10 UTC, AlreadyBored requested changes

2022-06-05 13:10 UTC, AlreadyBored commented on assignments/authentication/assignment.md
> +- Task can be implemented in Typescript
Please remove this line

2022-06-05 13:10 UTC, AlreadyBored commented on assignments/authentication/assignment.md
> +- Use [template](https://github.com/rolling-scopes-school/nodejs-course-template/generate)
Please remove this line, it should be only in template-rest assignment

2022-06-05 13:10 UTC, AlreadyBored commented on assignments/authentication/assignment.md
> +1. Implement **POST** `api/auth/signup` method (instead of **POST** `api/users`) that accepts **JSON** `login`, `password` and server responses with HTTP **200** code and relevant message on success.
Don't forget to make sure your changes are syncrohized with openapi spec in tempate

2022-06-05 13:10 UTC, AlreadyBored commented on assignments/authentication/score.md
> +## NB! For the succesfull tests results user with login = **admin**, and password = **admin** should be saved into DB.
If we implement signup, this is no longer needed

2022-06-05 13:10 UTC, AlreadyBored commented on assignments/logging-error-handling/assignment.md
> +- Use [template](https://github.com/rolling-scopes-school/nodejs-course-template/generate)
Same as above

2022-06-05 13:10 UTC, AlreadyBored commented on assignments/template-rest/assimnent.md
> +NB! You must create new repository from [template](https://github.com/rolling-scopes-school/nodejs-course-template/generate) for this task. Its name must be nodejs2022Q1-service i.e. full link to the
2022Q2

2022-06-05 13:10 UTC, AlreadyBored commented on assignments/template-rest/score.md
> +- **+15** The application code that worked with `favourites` instance divided into modules according to to its purpose (e.g.: work with request and response in *.router.js, business logic *.service.j
We should follow Nest.js architecture conventions, so let's say something like `divided into modules by its purpose according to Nest.js architercture rules` (just example)

2022-06-05 13:10 UTC, AlreadyBored commented on assignments/template-rest/score.md
>  - **+30** Task implemented on Typescript
Nest.js uses TS out of the box, please, remove this line

2022-06-08 14:12 UTC, ML6503 commented on assignments/authentication/assignment.md
> +1. Implement **POST** `api/auth/signup` method (instead of **POST** `api/users`) that accepts **JSON** `login`, `password` and server responses with HTTP **200** code and relevant message on success.
As decided waiting for final sample Library API project to make all amendments accordingly

2022-06-08 14:27 UTC, ML6503 commented on assignments/template-rest/score.md
>  - **+30** Task implemented on Typescript
removed

2022-06-08 14:28 UTC, ML6503 commented on assignments/template-rest/score.md
> +- **+15** The application code that worked with `favourites` instance divided into modules according to to its purpose (e.g.: work with request and response in *.router.js, business logic *.service.j
Amended by your sample. Thank you

2022-06-08 14:28 UTC, ML6503 commented on assignments/template-rest/assimnent.md
> +NB! You must create new repository from [template](https://github.com/rolling-scopes-school/nodejs-course-template/generate) for this task. Its name must be nodejs2022Q1-service i.e. full link to the
corrected

2022-06-08 14:28 UTC, ML6503 commented on assignments/logging-error-handling/assignment.md
> +- Use [template](https://github.com/rolling-scopes-school/nodejs-course-template/generate)
removed

2022-06-08 14:28 UTC, ML6503 commented on assignments/authentication/score.md
> +## NB! For the succesfull tests results user with login = **admin**, and password = **admin** should be saved into DB.
removed

2022-06-08 14:28 UTC, ML6503 commented on assignments/authentication/assignment.md
> +1. Implement **POST** `api/auth/signup` method (instead of **POST** `api/users`) that accepts **JSON** `login`, `password` and server responses with HTTP **200** code and relevant message on success.
removed

2022-06-08 14:28 UTC, ML6503 commented on assignments/authentication/assignment.md
> +- Use [template](https://github.com/rolling-scopes-school/nodejs-course-template/generate)
removed

2022-06-08 14:28 UTC, ML6503 commented on assignments/authentication/assignment.md
> +- Task can be implemented in Typescript
removed

2022-06-10 21:28 UTC, closed without merging