docs: add library to description and fix typo in api
AlreadyBored/nodejs-assignments pull request #94
Opened 2024-10-22 20:00 UTC by PavelOreshkin

1. added ts-loader in libraries list, because a lot of student ask "can we use ts-loader?", and I also try to find answer, and figure out that this question appear every time (it scare to add this library, because it doesn't have in list and have a risk to get -95% to score)

2. fix typo from "user" to "users", because we dont have api "/user/{userId}"

2024-10-22 20:01 UTC, PavelOreshkin commented
@AlreadyBored

2024-11-02 18:22 UTC, AlreadyBored requested changes

2024-11-02 18:22 UTC, AlreadyBored commented on assignments/crud-api/assignment.md
> +- Only `nodemon`, `dotenv`, `cross-env`, `typescript`, `ts-node`, `ts-node-dev`, `ts-loader`,`eslint` and its plugins, `webpack-cli`, `webpack` and its plugins, `prettier`, `uuid`, `@types/*` as well
I would propose more generic approach here

```suggestion
- Only `nodemon`, `dotenv`, `cross-env`, `typescript`, `ts-node`, `ts-node-dev`, `eslint` and its plugins, `webpack-cli`, `webpack` and its plugins and loaders, `prettier`, `uuid`, `@types/*` as well as libraries used for testing are allowed
```

2024-11-24 16:15 UTC, AlreadyBored approved these changes

2024-11-24 16:15 UTC, merged